# Generated by Django 3.1.5 on 2021-01-07 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aparna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=20)),
                ('your_email', models.EmailField(max_length=254)),
                ('your_cmt', models.TextField()),
            ],
        ),
    ]
